### ISSUE TITLE
Replace config path override options with bundle directory option.

### ISSUE THREAD

**Issue by mikebrow** [wking/oci-command-line-api#12]
See: https://github.com/opencontainers/runc/pull/373 
The config files MUST be located in the root of the bundle directory. Will fix runtime.md when the other changes drop. Dupe..

**Comment by wking** [comment]
On Thu, Dec 10, 2015 at 12:10:28PM -0800, Mike Brown wrote:

> See: https://github.com/opencontainers/runc/pull/373 
> The config files MUST be located in the root of the bundle directory. 

Dup of #11?

**Comment by mikebrow** [comment]
Yes, dup..  my bad.. may need some discussion about the config files used for start, but lets let these changes pop.
